[package]
name = "qudag-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
qudag-crypto = { path = "../crypto" }
qudag-dag = { path = "../dag" }
qudag-network = { path = "../network" }
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
proptest = { workspace = true }
