[package]
name = "qudag-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
pqcrypto = { workspace = true }
rand = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
