# QuDAG Node 1 - Toronto (yyz) - Bootstrap Node
# Updated configuration with proper health checks and settings

app = "qudag-testnet-node1"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "../Dockerfile.production"

[build.args]
  NODE_TYPE = "bootstrap"
  NODE_NAME = "toronto-node"

[env]
  RUST_LOG = "info,qudag=debug"
  RUST_BACKTRACE = "1"
  QUDAG_NODE_NAME = "toronto-node"
  QUDAG_NETWORK_ID = "qudag-testnet"
  QUDAG_DARK_DOMAIN_ENABLED = "true"
  QUDAG_P2P_PORT = "4001"
  QUDAG_RPC_PORT = "8080"
  QUDAG_METRICS_PORT = "9090"
  QUDAG_CONFIG_PATH = "/data/qudag/config.toml"
  # Bootstrap node specific
  QUDAG_BOOTSTRAP_MODE = "true"
  QUDAG_REGISTRY_AUTHORITY = "true"
  QUDAG_IS_BOOTSTRAP = "true"

[experimental]
  auto_rollback = true
  enable_consul = false

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = false

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "45s"
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 3
    [services.http_checks.headers]
      X-Node-Type = "bootstrap"

# P2P Port - TCP
[[services]]
  internal_port = 4001
  protocol = "tcp"
  processes = ["app"]
  
  [[services.ports]]
    port = 4001

# P2P Port - UDP (for QUIC transport)
[[services]]
  internal_port = 4001
  protocol = "udp"
  processes = ["app"]
  
  [[services.ports]]
    port = 4001

# Metrics endpoint
[[services]]
  internal_port = 9090
  protocol = "tcp"
  processes = ["app"]
  
  [[services.ports]]
    port = 9090
    handlers = ["http"]
  
  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  size = "shared-cpu-2x"
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[mounts]
  source = "qudag_data_node1"
  destination = "/data/qudag"

# Docker ENTRYPOINT handles process execution

[[statics]]
  guest_path = "/app/configs/node1.toml"
  url_prefix = "/"

[[regions]]
  yyz = 1  # Primary region (Toronto)
  ord = 0  # Backup region (Chicago)
