[package]
name = "qudag-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
tokio.workspace = true
anyhow.workspace = true

# CLI specific dependencies
clap = { version = "4.0", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "std", "env-filter"] }
colored = "2.0"
tabled = "0.15"
dialoguer = "0.11"
indicatif = "0.17"
uuid.workspace = true
bincode.workspace = true
metrics.workspace = true

# Missing dependencies that were causing compilation errors
futures = "0.3"
lru = "0.12"
serde_json = "1.0"
pin-project = "1.0"
hex = "0.4"
rand = "0.8"

# Internal dependencies
qudag-protocol = { path = "../../core/protocol" }
qudag-network = { path = "../../core/network" }
qudag-dag = { path = "../../core/dag" }
qudag-crypto = { path = "../../core/crypto" }

[[bin]]
name = "qudag"
path = "src/main.rs"

[dev-dependencies]
proptest.workspace = true